### ISSUE TITLE
New default publication reference format

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#1001]
When providing a DOI in the curator, the initial publication reference format is:

```
first_name initial last_name, etc.
```

When searching for studies people often look for last name, so it might be better to have:

```
last_name, first_name initial, etc.
```

I _believe_ all phylografter studies all have the latter formatting.

**Comment by josephwb** [comment]
I should mention that the issue involves how studies are displayed on the [front page of the curator](https://tree.opentreeoflife.org/curator/).

**Comment by jimallman** [comment]
As an aid to choosing a better format... These "compact references" appear in a few other places: 

**Main title of each study page**

>  <img width="616" alt="screen shot 2016-07-20 at 1 40 00 pm" src="https://cloud.githubusercontent.com/assets/446375/16996493/8ffcce80-4e7f-11e6-907a-65845fb21767.png">

**Search results when adding a tree to a collection**

>  <img width="433" alt="screen shot 2016-07-20 at 1 47 31 pm" src="https://cloud.githubusercontent.com/assets/446375/16996765/a399a9f8-4e80-11e6-81a0-8b775569dd7b.png">

**Description of a tree in a collection**

>  <img width="374" alt="screen shot 2016-07-20 at 1 45 56 pm" src="https://cloud.githubusercontent.com/assets/446375/16996684/5d990660-4e80-11e6-9920-33cbee16d759.png">

**Comment by jimallman** [comment]
@josephwb, note (based on the examples above) that [the current `fullToCompactReference` function](https://github.com/OpenTreeOfLife/opentree/blob/9f6eece22c63d3f3457d712824165a51916280cc/curator/static/js/curation-helpers.js#L5-L16) often returns your desired format, but not always. This depends on how the full reference text is organized. I'll see if I can be more clever about how this parses the full reference...

**Comment by kcranston** [comment]
The underlying issue here is that `ot:studyPublicationReference` does not have a standardized format, making it difficult to guarantee consistency of the short form based on string parsing. We are currently generating the `ot:studyPublicationReference` from the DOI lookup with author lists in the format `Jente Ottenburghs, Hendrik-Jan Mergens` which then translates to a short publication reference of `Jente Ottenburghs, 2016` (because we split the first author based on the first comma in the author list). In contrast, if `ot:studyPublicationReference` contains  `Ottenburghs, Jente, Hendricks-Jan Mergens` then the short format is `Ottenburghs, 2016`. This screen shot shows the difference between the 'Current Reference Text' in one format and the string as suggested by the curator. We could try and make the short reference method smarter, or we could change the way that the curator builds that string from CrossRef, but curators could always change it (unless we make it an un-editable field).  

![screen shot 2016-07-27 at 1 04 36 pm](https://cloud.githubusercontent.com/assets/312034/17184543/cf55ab8a-53fa-11e6-8e84-3eca6c37e19f.png)

**Comment by kcranston** [comment]
I am going to close this, because I don't see a way to standardize the short reference without standardizing the long reference format, which is complicated because:

* the format returned by CrossRef is different from the phylografter studies
* the regex for separating author names would be complicated (and error-prone) 
* users can currently edit the publication reference field (and need to be able to do so, since not all studies have DOIs that can be queried by crossref)
* standardizing the format while allowing user editing would mean collecting each piece of the reference separately (author1 firstname, author 2 lastname, ... author 23 firstname, author23 lastname, etc) which seems like too much of a curator burden
