### ISSUE TITLE
Tree Collection editor can't find studies for second tree added

### ISSUE THREAD

**Issue by DMaddison** [OpenTreeOfLife/opentree#1029]
This is for collection Adephaga.  Go into collection, choose Edit.  Ask to add a tree from Maddison 2012.  Add the tree.  Ask to add another tree.  When you then type "Maddison" in the "by matching a study" box, it won't find anything.   It seems as if you need to fully reload your profile page in order to get that functionality back

**Comment by jimallman** [comment]
@DMaddison, thanks for your patience. I was having some trouble reproducing this, but I believe the problem is due to some code that abandons a search if the string is unchanged from last time (for example, your repeated use of the string "Maddison"). I underestimated the changes that a browser's autocomplete features, or someone typing > 1 char per second, would repeat a search.

This fix should reach production late this week; for now, it's [available for review on **devtree**](http://devtree.opentreeoflife.org/curator/collections). In the meantime, you can keep adding trees on production; just change the text (backspace) and wait ~1 second before restoring it.
