### ISSUE TITLE
trouble setting root

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1035]
I am trying to re-root this tree:

https://tree.opentreeoflife.org/curator/study/edit/ot_766/?tab=trees&tree=Tr85440&conflict=ott

The editor has a polytomy at the root (blue, Tr85440_ROOT), and an extra node (orange, Tn12578815) between the marked root and one of the two ingroup clades. This is easiest to see in radial mode - screen shot attached. In this case, the root should be on the long blue branch between Tr85440_ROOT (aligned with cellular organisms) and Tn12578697 (aligned with Bacteria). As is, I can't set the ingroup, because there is no node that is the ancestor of the the two clades that aren't Bacteria - the clade at the top left of the screen shot. 

<img width="373" alt="screen shot 2016-08-21 at 10 12 29 am" src="https://cloud.githubusercontent.com/assets/312034/17837694/cea7cb3c-6787-11e6-8bae-f5c6f581e926.png">

**Comment by jimallman** [comment]
We long ago disabled rooting from root-adjacent edges... I can't recall why, but I will dig through past issues and report back here. (Perhaps we didn't account for a polytomy at the root? but that seems unlikely..)

Meanwhile, I think you can accomplish this as follows:
  - temporarily re-root to another edge (I tried the orange one just past the "knuckle")
  - find the desired edge (between old root and Bacteria) and re-root to it
  - I believe you'll now find a sensible ingroup node

Here's my result (_unsaved_ changes on **devtree**):

![screen shot 2016-08-23 at 4 22 03 pm](https://cloud.githubusercontent.com/assets/446375/17908288/da009be0-694d-11e6-9527-1958129be336.png)

**Comment by jimallman** [comment]
Here's [some prior discussion](https://github.com/OpenTreeOfLife/opentree/issues/919) of when it's appropriate to re-root from an edge that's adjacent to the root node, and [the pull request that implemented the current behavior](https://github.com/OpenTreeOfLife/opentree/pull/960).

Here we've considered the case above _(re-rooting from an edge that's adjacent to the root, when the root is an ah-hoc node)_ as one in which the desired re-rooting would have no effect (it's a "no-op"), so we block the option in the UI.

This is because the ad-hoc root node (identifiable by a decorated id like `Tn123_ROOT`) should have been created by a prior rooting on a single edge. **So it should never have a polytomy, and yet it does.** We'll need to retrace the history of this tree's curation to see how this happened.

**Comment by snacktavish** [comment]
I'm not clear on why the ad-hoc root node should never be a polytomy. But maybe I don't know what 'ad-hoc root node' means. A tree can come in with a polytomy as the root, right?

**Comment by jimallman** [comment]
Right, and any incoming tree will have a "normal" root node. If a curator re-roots the tree on an edge, we create an ad-hoc root node and an ad-hoc, adjacent edge. We keep track of these (in the curation app's JS and in Nexson) using special IDs with `_ROOT` (or `_ROOT_EDGE') appended.

In other words, re-rooting on an edge should result in an ad-hoc root node with just two children -- the former parent and child node of that edge. How we wound up with an ad-hoc root with polytomy is the mystery...

**Comment by snacktavish** [comment]
ah, I see! Thanks for the clarification.

**Comment by jimallman** [comment]
In reviewing [the curation history for this tree](https://tree.opentreeoflife.org/curator/study/edit/ot_766/?tab=history), it looks like it was re-rooted twice, in each of the last two revisions. The first time [appears to have created the expected ad-hoc root and edge](https://github.com/OpenTreeOfLife/phylesystem-1/commit/b73c8af2b07b3515de881a3d1a5eb514fb74fc91) as expected. The second time [apparently added a new child edge to the ad-hoc root](https://github.com/OpenTreeOfLife/phylesystem-1/commit/280b3bc191a6530161a1b32ac20b05c2b4ff6a05) but didn't(!) remove either of the old ones. If I'm reading this correctly, this change actually mangled the tree, likely due a bug in my JS, [somewhere around here](https://github.com/OpenTreeOfLife/opentree/blob/f52397bc968c24061467e1478bf4a6f899e0c057/curator/static/js/study-editor.js#L4525-L4546). I should be able to retrace the steps here and fix this.

**Comment by jimallman** [comment]
Update: I'm able to reproduce this bug in other trees. It's kind of an edge case -- you need to re-root a few times, both with and without using the ad-hoc elements -- but it can definitely mangle the tree. :grimacing: 

Once I've sorted out a proper fix, I'll start working on a test of the existing phylesystem corpus to find (or at least narrow down) any studies that might need review.

**Comment by mtholder** [comment]
It would definitely be good to go through the corpus and check that the rooting did not change the tree shape, but you can assign that part of the task to me.
I know how to get DendoPy to tell us the unrooted tree difference between 2 trees (or at least I can remind myself how to do it with DendroPy). That should stay 0 regardless of rooting, so it should not be hard to spot problems.

**Comment by jimallman** [comment]
> I know how to get DendoPy to tell us the unrooted tree difference between 2 trees

That is a huge relief. Thanks!

**Comment by jimallman** [comment]
I have a fix (working for me) available on **devtree**. 

@kcranston To test this against your tree, please see [the same TreeBASE study and tree on devtree](https://devtree.opentreeoflife.org/curator/study/edit/tt_104/?tab=trees&tree=Tr85440). You should now be able to set its root as desired, with no polytomy from the ad-hoc root node (Tr85440_ROOT).

**Comment by jimallman** [comment]
I'm hoping there will be very few trees in the system affected by this. To be clear, this is the edge case that produces the error:
  1. Re-root a tree on an edge (creating the ad-hoc root node and edge)
  2. Re-root the tree to an existing node (we now have unused/latent ad-hoc elements)
  3. Re-root one more time, to another edge. A weird new polytomy appears.

During step 2, it's possible for the latent ad-hoc edge to be "flipped", reversing its `@source` and `@target` properties. The new code catches this whenever the ad-hoc elements are called back into service (step 3) and restores its natural polarity, preserving the tree structure.

A more thorough fix might be to remove the ad-hoc root elements entirely when they're not being used, rather than simply detaching them and keeping them latent in the tree. For now I'm [trying not to shake the Jello](http://nedbatchelder.com/blog/200508/kent_beck_software_health.html).
