### ISSUE TITLE
link to onezoom

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1051]
Now that [OneZoom](http://onezoom.org) has an opentree visualization, we should link to it somewhere in the tree browser.

**Comment by kcranston** [comment]
@hyanwong notes [on gitter](https://gitter.im/OpenTreeOfLife/public?at=57daffe0aabc89857fa6b5d7):

There is a direct link from OTT numbers to our URLs. So e.g. OTT 343294 can be turned straight into http://www.onezoom.org/life.html/@=343294

**Comment by hyanwong** [comment]
Any help we can give from the OneZoom end, just let me know. I'll follow this git issue.

**Comment by jimallman** [comment]
This is working now on **devtree**. The link to OneZoom appears (for OTT taxa only) below the link to EOL. 

In some cases, the result is as expected:

 - [Browse 'Mammalia' in OneZoom](http://www.onezoom.org/life.html/@=244265)
 - [Browse 'Amniota' in OneZoom](http://www.onezoom.org/life.html/@=229560)

In others, the result is targeted, but the accuracy isn't clear to me:

 - [Browse 'Opisthokonta' in OneZoom](http://www.onezoom.org/life.html/@=332573)

Sometimes the view doesn't seem to highlight any particular node (shows root of tree):

 - [Browse 'Bacteria' in OneZoom](http://www.onezoom.org/life.html/@=844192)
 - [Browse 'Candidatus Carsonella' in OneZoom](http://www.onezoom.org/life.html/@=4790637)
 - [Browse 'Prototheria' in OneZoom](http://www.onezoom.org/life.html/@=962395)

**Comment by hyanwong** [comment]
Great, thanks. 

The 'Opisthokonta' link is correct. We try to fit al descendants of a node onto the screen.

For taxa not on the tree (e.g. eubacteria), it will go to the root. We have yet to implement a popup that says "sorry, this taxon is not on the OneZoom tree". This may also apply to some other taxa present on the OpenTree but not on OneZoom: for instance we cull certain identified fossils, and have our own mammal tree.

Conversely, there are some taxa that have OTTs but are missing from the synth tree (e.g. due to _incertae sedis_), but which *are* on OneZoom, e.g. http://www.onezoom.org/life.html/@=3599889

**Comment by hyanwong** [comment]
Once https://github.com/OpenTreeOfLife/opentree/issues/1054 is implemented we'll provide a link back to the OpenTree in the tab popups.

**Comment by kcranston** [comment]
Resolved with PR #1059
