### ISSUE TITLE
Label taxon nodes in tree viewer

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#1064]
It would be nice in the curator when looking at a tree to see nodes labelled with higher taxa (genus, family, etc.). I think this would greatly cut down the chase for badly-mapped taxa (re: https://github.com/OpenTreeOfLife/opentree/issues/877)

**Comment by jar398** [comment]
note that the required information is provided by the conflict analysis
service. it is a matter of displaying it in the tree view, instead of just
in the node mouseovers.

**Comment by kcranston** [comment]
Also note that if the tree already contains internal node labels, the tree viewer displays them, e.g. [this Ruggiero taxonomy](https://devtree.opentreeoflife.org/curator/study/view/tt_150/?tab=trees&tree=tree1). Couple of thoughts:

* we might need to decide how to handle hide / show when there are multiple node labels
* possibility of reporting differences between inferred label and stated label
* allowing curators to add labels to internal nodes

**Comment by josephwb** [comment]
I would speculate that < 1% have such labels. Is it even useful to collect those if we are mapping to our own taxonomy?

**Comment by jar398** [comment]
I'd say, if there is both a label from the nexson and an inferred label, just show the one from the nexson. The other one is easily seen with a mouse over.

Extra credit:

If the inferred labels were hyperlinked to the taxonomy browser that would be heavenly.

If the conflict analysis was against the synthetic tree, the inferred labels (whatever they are) could take you to the tree browser.

**Comment by arlin** [comment]
I have a related issue, in regard to induced subtrees.  If you query for an induced subtree with a list that includes Ursus species1 and Ursus species2, even if these are the only Ursus species, the node uniting them is not necessarily labeled "Ursus". I can imagine why this would happen due to the way subtrees are extracted. At the front end, however, this annoys users: what they see is that some nodes get their expected labels, and others don't.

Suppose you wanted to fix this in the back end, by harvesting taxon names during subtree extraction, in a way that is most useful or intuitive to users.   Gather taxonomic names along a collapsed lineage, and choose the most appropriate by a set of rules, e.g., if > 1 name, prefer a name of full rank; if > 1 full rank name, pick the lowest (or perhaps highest, depending on client preference). Could that be done?  This actually sounds like a separate issue from the one being discussed here.

**Comment by jimallman** [comment]
> I'd say, if there is both a label from the nexson and an inferred label, just show the one from the nexson. The other one is easily seen with a mouse over.

I've implemented this on **devtree**, see for example [this tree](http://devtree.opentreeoflife.org/curator/study/edit/pg_2606?tab=trees&tree=tree6049&conflict=synth) with either conflict view. I've also slightly improved the popup explanation to explain where this label is coming from.

Note that with these changes, we'll [show node labels based on the first match](https://github.com/OpenTreeOfLife/opentree/blob/9e7c079541c91a14cf71ffa93831c07f6a3dbe2d/curator/static/js/study-editor.js#L5188-L5229) below:
1. If node (tip) has an OTU, _and_ it's mapped to a taxon, show the mapped name.
2. If node (tip) has an unmapped OTU, show its original name.
3. If node has `@label` _and_ its `^ot:nodeLabelMode` is `ot:other`, treat this label as a taxon name and show it. 
4. If node has `conflictDetails` _and_ its conflict status is one of `['supported_by', 'partial_path_of', 'mapped_to_taxon']` _and_ it has a `witness_name`, show this witness name (taxon). 
5. If node has `@label` _and_ it has `^ot:nodeLabelMode` (any value), show this 'label' as a support value.
5. If node has `@label` _and_ it has no `^ot:nodeLabelMode`, show this 'label' as ambiguous.
6. If node's adjacent (root-ward) edge has a label, show it as a support value.
7. If none of the above apply, show any empty label (only visible when highlighting node).

> If the inferred labels were hyperlinked to the taxonomy browser that would be heavenly.
>
> If the conflict analysis was against the synthetic tree, the inferred labels (whatever they are) could take you to the tree browser.

To confirm: The main node label (not the one in the node's popup) would be a hyperlink? This should be a pretty easy addition, if so. Would this behavior also apply to tip labels (maybe just those mapped to the taxonomy)?

**Comment by jimallman** [comment]
> To confirm: The main node label (not the one in the node's popup) would be a hyperlink?

I've gone ahead and made this change, but for internal nodes only:
<img width="370" alt="tool-tip" src="https://cloud.githubusercontent.com/assets/446375/20898356/03006abe-baf4-11e6-83db-2577a1c5255f.png">


This is working now on **devtree**.

**Comment by jar398** [comment]
Hate to throw another wrench in the works, but it's possible for a tip's
node id and taxon name in the nexml file to differ from the taxon name and
id returned by conflict results.  If both are present, the conflict result
is more reliable in the sense of better reflecting the current taxonomy
(and therefore synthesis) - species get renamed, lumped, and so on. If the
conflict item is absent, that means the taxon has been deleted from the
taxonomy. I don't think it can happen for there to be a conflict result but
no OTTid in the nexml.

It's pretty safe to just show OTT id/name from the nexml since these
differences are rare. On the other hand the information might be important
in some (also very rare) cases. So maybe the option of showing both, or the
addition of an indicator noting that there is a difference, should be
recorded as a separate very-low-priority issue.

**Comment by kcranston** [comment]
These changes look good, Jim! Thanks.

**Comment by jimallman** [comment]
> ... it's possible for a tip's node id and taxon name in the nexml file to differ from the taxon name and
id returned by conflict results.

This is surprising to me. How would the conflict service assign tip names with any confidence, since all it knows about the tip is its parent node and _n_ named siblings? Is it reading the old label and surmising a rename or the like?

**Comment by jar398** [comment]
Between the time the OTU id and name were stored in the Nexml, and the time
the conflict report is viewed, the original may have been merged (lumped)
with another record, or the name may have been changed by the source
taxonomy, e.g. A genus move or spelling correction.

-- apologies for brevity / using handheld gizmo --

On Dec 6, 2016, at 10:07, Jim Allman <notifications@github.com> wrote:

... it's possible for a tip's node id and taxon name in the nexml file to
differ from the taxon name and
id returned by conflict results.

This is surprising to me. How would the conflict service assign tip names
with any confidence, since all it knows about the tip is its parent node
and *n* named siblings? Is it reading the old label and surmising a rename
or the like?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenTreeOfLife/opentree/issues/1064#issuecomment-265190787>,
or mute the thread

**Comment by jimallman** [comment]
I've spawned a new (low priority) issue #1132 from @jar398's comment above. @josephwb, OK to close this?

**Comment by josephwb** [comment]
Yerp.
