### ISSUE TITLE
Review new include-in-synthesis UI

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1101]
<img width="735" alt="screen shot 2016-11-23 at 9 27 27 am" src="https://cloud.githubusercontent.com/assets/312034/20565316/14ae9ac2-b15f-11e6-918b-20084030f596.png">

**Comment by kcranston** [comment]
Couple of initial thoughts:

* all of the options appear to be greyed out initially. It isn't until you roll over a tree that you can tell which buttons are active
* the difference between inactive and active is very slight and hard to differentiate
* when I click on the (greyed out) include button for the Happy Tree, I get the message "This tree needs further curation (confirmed root node)." 
* I wonder if status for trees without sufficient curation should be "Needs curation" rather than "Needs review".
* when I click on Include for the Sad panda tree!, the tree gets added to the default collection but the status does not change from 'Needs review'. 
* Is the addition to the default collection conditional on saving the study? If I close the study without saving, is the tree in the collection?
* It would be good (version 2!) to give a user more feedback about ranking, other collections, etc.

**Comment by jimallman** [comment]
Thanks for fresh eyes!

> all of the options appear to be greyed out initially. It isn't until you roll over a tree that you can tell which buttons are active

Yes, we use "ghosted" widgets in all similar tables in the webapp, mainly to avoid the visual noise of lots of red buttons, etc. It is confusing here, since opacity is important to understanding these buttons. I'll disable the ghosted effect on this tab and see how it looks.

> the difference between inactive and active is very slight and hard to differentiate

This is based on Bootstrap's style. If removing the ghosting (above) doesn't help to clarify the difference, I'll try to accentuate it further.

> when I click on the (greyed out) include button for the Happy Tree, I get the message "This tree needs further curation (confirmed root node)."

This is intentional, to explain [what specific steps will enable inclusion](https://github.com/OpenTreeOfLife/opentree/pull/1100/files#diff-ec50a802bd4aa427fc715b6e1989c6a2R3133) for each tree.

> I wonder if status for trees without sufficient curation should be "Needs curation" rather than "Needs review".

This might help to set expectations, yes. I'll try it.

> when I click on Include for the Sad panda tree!, the tree gets added to the default collection but the status does not change from 'Needs review'.

Hm, that's just a bug. These status lines should definitely update immediately.

> Is the addition to the default collection conditional on saving the study? If I close the study without saving, is the tree in the collection?

Inclusion and exclusion happen immediately, by manipulating the collections via AJAX. This can lead to situations where someone has curated the tree (e.g. by confirming its root node), including it, then not saving the study. In this case, the study sneaks into synthesis without passing muster. Would this be hard to catch downstream?

We can avoid this by forcing a save of the study, or by postponing the inclusion/exclusion until after a save. The latter option complicates things quite a bit, since we'd need to track "pending inclusion/exclusion" in the study, any errors will be difficult to report to the user, and they're just as likely to be confused if they don't save.

> can that 'Include in synthesis' column heading span the label + buttons? Also, the function of the 'x' button is less clear now.

Ah, I didn't notice the column headings are out of joint. Will review and fix this next.

**Comment by jimallman** [comment]
OK, please [check out these revisions](https://devtree.opentreeoflife.org/curator/study/edit/pg_2606?tab=trees) on **devtree**:

 - Restored all "ghosted" widgets to full opacity
 - Reduced opacity of all disabled buttons for greater clarify
 - Softened "error" messages to "info" (blue) when clicking a disabled Include/Exclude button
 - Added a gap to the left of the delete-tree button, to avoid confusion
 - Revised tree-list headings (and removed junk Yes/No column)
 - Fixed all synth-status indicators to respond immediately to changes
 - Added "Needs curation" status for trees that need confirmed rooting or OTU mapping
 - Modified some trees at the URL above, to show more of the UI

Don't forget to check [the read-only view](https://devtree.opentreeoflife.org/curator/study/view/pg_2606?tab=trees) as well, as it's obviously a bit different. Note how the little badge (to show the synth-details popup) is right next to the status text here; should this be true on the "edit" page as well? Given that we have Include and Exclude buttons in the popup, do we want to keep the mini versions in the list, too?

**Comment by snacktavish** [comment]
Looks good! I like the plan of exclude popping up a message to grab reasons.
I was confused by the request to save when navigating away.
This is maybe a more general comment, but it would be nice if the tree warnings were associated with each tree. e.g. the first tree says it needs curation, but it isn't obvious which one of the error above apply to it.

**Comment by jimallman** [comment]
>  I like the plan of exclude popping up a message to grab reasons.

Agreed. I've added this, along with more helpful footer messages and a few other touches, to the latest on **devtree**. See the latest commit messages in #1100 for details.

**Comment by jimallman** [comment]
@kcranston Please see all the latest on **devtree**, perhaps using the [edit](https://devtree.opentreeoflife.org/curator/study/edit/pg_2606?tab=trees) or [read-only](https://devtree.opentreeoflife.org/curator/study/view/pg_2606?tab=trees) views of my preferred example study. Here are the highlights:
 - Use trashcan icon for (persistent) object removal.
 - Move synth-status icon alongside text description.
 - Prompt for reasons to exclude from synthesis, and for override when including when there are reasons already.
 - Offer more informative messages to clarify that "excluding a tree" means building a list of reasons-to-exclude.
 - Support confirmation of tree root from node menu (in tree view), and reciprocal relationship between this control and the confirmed-root radio button we already offer.

See the latest commit messages in #1100 for more details on these changes.
