### ISSUE TITLE
Trees drawn differently on different browsers

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#1106]
It seem that trees are drawn differently on different browsers? For [this tree](https://tree.opentreeoflife.org/curator/study/edit/ot_1003?tab=trees&tree=Tr100304), on Safari, all outgroups are at top of screen, but on Opera they split on top and bottom. Firefox behaves like Opera for this tree.

These configurations are just rotated, so they are valid, but was unexpected. Maybe we need a default ladderization setting to make things consistent?

**Comment by jimallman** [comment]
As a reminder, the prior sorting-related issues are #625 and #1000.

**Comment by jimallman** [comment]
OK, I've set up a common sort-and-ladderize function that works consistently across browsers. This now applies to both the standard _and_ radial (circular) tree layouts, since the latter was subject to arbitrary rotation as well as inconsistent node order across browsers.

See the results on **devtree**, [for example this tree](https://devtree.opentreeoflife.org/curator/study/view/ot_535/?tab=trees&tree=tree1).

**Comment by josephwb** [comment]
Looks great for this example!

**Comment by jimallman** [comment]
Thanks. Hopefully this will avoid head-scratching in the future, esp. for collaborators using different browsers.
