### ISSUE TITLE
curator is exporting obsolete ot namespace URLs in nexson and NeXML

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/opentree#1119]
Curator (invoking the API directly) is exporting nexson files that refer the ot namespace to http://purl.org/opentree-terms#, and NeXML files that refer to http://purl.org/opentree/nexson.  The first one gives a "not found" error and the second one redirects to a "this file has moved" message (http://opentree.wikispaces.com/NexSON) directing the user to the correct URL which is https://github.com/OpenTreeOfLife/phylesystem-api/wiki/NexSON.  

Examples: 
* https://api.opentreeoflife.org/v3/study/ot_639?output_nexml2json=1.2
* https://api.opentreeoflife.org/v3/study/ot_639.nexml

**Comment by jar398** [comment]
The correct URL should be a purl.org URL.
It cannot be purl.org/opentree-terms# because there is no way to adminster that. opentree/nexson is better.
It should redirect to https://github.com/OpenTreeOfLife/phylesystem-api/wiki/NexSON.
The wikispaces URL is not current. The PURL might redirect someplace else in the future.
I'm trying to figure out how do purl administration following purl.org's move from OCLC to IA, will get back to you.

**Comment by jar398** [comment]
The nexson looks fine; of course the URL should be resolvable, and I'm working to fix that, but that should be immaterial from a software perspective. It's the json that has a bad namespace URL, and I think that needs to be fixed in peyotl.

**Comment by jar398** [comment]
I think there is only one thing to be done, and that is fixing peyotl. Perhaps @mtholder would like to create a properly worded peyotl issue, and close this one? If not then I will create a peyotl issue.

I have recovered authorization to maintain purl.org/opentree URLs, and have changed http://purl.org/opentree/nexson  to redirect to   https://github.com/OpenTreeOfLife/phylesystem-api/wiki/NexSON. But this does not do anything to fix the original problem.

Our PURLs are listed here: https://github.com/OpenTreeOfLife/germinator/wiki/Open-tree-PURLs

**Comment by mtholder** [comment]
should be fixed with https://github.com/OpenTreeOfLife/peyotl/tree/phylesystem-1-issue-14
