### ISSUE TITLE
Question/Warning regarding server load

### ISSUE THREAD

**Issue by wellcaffeinated** [OpenTreeOfLife/opentree#1176]
Hi there!
Firstly, thanks for building this. It's an amazing project.

I'm the main developer behind minutelabs.io, a (long dormant) project surrounding building sciencey apps to tickle the curiosity of the general public.

I've nearly finished building an app based on the OTL database. (Working title: Tree of Life Explorer). It's a fully client-side app that fetches data from OTL, GBIF, WORMS, Wikidata, Wikimedia and assembles it based on user input. In short: You can build some cool phylogenetic trees with pictures and stuff.

http://labs.minutelabs.io/Tree-of-Life-Explorer

Currently it's not yet public. (please refrain from sharing widely for a bit)

In the past when we've released our "Labs" some of them have gotten around 12k hits on the first day. At the moment our app can occasionally generate upwards of 100 hits to your server per tree generation. This would amount to a possible ~1.2 Million hits to your server in a day. I just want to make sure that your server can handle that. (I'm caching as much as i can)

Also, if there's any kind of credit note or link you want me to include on the app I'm very happy to do that. :)

If you have any questions let me know!

**Comment by mtholder** [comment]
Hi,  Thanks for interest in the project and the the heads up about the possible traffic! I am pretty sure that the current configuration of servers would not be able to handle that much traffic.

A couple of questions:
   1. Do you know what API methods your app would be calling (or calling most frequently)? (I guess I can look through the code at https://github.com/minutelabsio/Tree-of-Life-Explorer ...)
   2. Do you have an approximate timeframe for release?

One pointer: I don't know if you've seen the http://phylotastic.org/ project, they make tools for integrating phylogenetic info with audiences including scientists and the general public.

Some possibilities on increasing our maximum capacity...
The good news is that most of what the site does is serve views of static artifacts (the current synthesis tree and the current version of the taxonomy). So, it should be relatively easy to get higher capacity by just deploying more servers.

  A. a short term hack:  An easy adjustment would be for us to spin up some more machines, and register them in dns as something like api1.opentreeoflife.org, api2, api3... If there was some way that the client code could make a random decision about which backend to talk to (talking to the same backend would be better in terms of dealing with latency caused by session acquisition).   We could method to the API  that reports the set of identical backends (the set of api1.opentreeoflife.org, api2.opentreeoflife.org domains...) such that clients could check API first and then make an arbitrary decision of the sake of load balancing.

  B. longer term: api.opentreeoflife.org should delegate calls to other servers as needed so that clients don't have worry about talking to different machines.

I'll try to look into benchmarking and solution B next week and get back to you.

**Comment by wellcaffeinated** [comment]
The primary endpoints i hit are:
- `/tree_of_life/node_info`
- `/tnrs/match_names`

If there were a way to search TOL node info by GBIF id, I wouldn't even need `match_names`.

We don't have a specific release date but would love to release it quite soon... we wanted to do some beta testing asap. 

If it's serving static assets, I wonder if there's a way to cache the data (cloudflare??). If you want to use your solution "A" that's fine by me. I can modify the code pretty easily to accommodate that. But seems like overkill for a single day of traffic.

**Comment by snacktavish** [comment]
The app looks very cool! 

All of the gbif ids are mapped to the open tree ids in the taxonomy dump files at - https://tree.opentreeoflife.org/about/taxonomy-version/ott3.0, if that helps.  It could let you skip the name resolution with can be a bit slow.

It would be great if in the 'about' or on the main page it specified that the relationships were coming in from Open Tree of Life.

**Comment by wellcaffeinated** [comment]
Ah cool!
But it looks like I'd need to build an API out of that dump file to get the relationships. I'd also need to index it by gbif id. 

My hope is that one day you'll implement `tree_of_life/node_info` to accept a payload of `{ gbif: '12345' }` :)

**Comment by mtholder** [comment]
note that you can get the ott id from an api call such as:

    curl -X POST https://api.opentreeoflife.org/v3/taxonomy/taxon_info -H 'content-type:applicatin/json' -d '{"source_id":"gbif:8141286"}'

and then get the node using `tree_of_life/node_info`. 
It appears to me that there are not any cases of GBIF ids that map to multiple OTT Ids. (I found 13132 cases of the opposite: OTT Ids that have multiple GBIF ids).  That kinda surprises me.

If that is the case, then we could add an unambiguous look up of nodes in the tree from GBIF ids. I'd suggest that @bredelings  or I think about adding to otcetera a `'{"source_id":"gbif:8141286"}'` syntax as an optional argument (instead node ID) for the node_info call. Thoughts, @bredelings ?

**Comment by wellcaffeinated** [comment]
Fantastic!
Another problem I had was ensuring that a specific GBIF entry corresponded to an actual true node in the synthetic tree for the purposes of the search. Currently I'm doing a bulk name match of the gbif autocomplete results and crosschecking with OTL. Any chance there's an easy way to take a list of gbif entries and verify they exist in the synthetic tree? (https://github.com/OpenTreeOfLife/feedback/issues/420)

**Comment by jar398** [comment]
If I remember the method correctly, source id to OTT id mappings are _always_ unique when they exist. If the method finds two OTT nodes as mapping candidates and can't rule either one out, then it leaves the source id unmapped. This is fine since the unknown "correct" taxon in question is probably already in OTT and no contribution from the source taxonomy is needed.

**Comment by jar398** [comment]
Sounds related to this issue: https://github.com/OpenTreeOfLife/germinator/issues/80 ?

**Comment by bredelings** [comment]
I just saw this.

Hmm... I just saw this.  I'll look into this tomorrow.

-BenRI

**Comment by wellcaffeinated** [comment]
Hi there! @mtholder Any update on this?

**Comment by bredelings** [comment]
Hi @wellcaffeinated, I'm looking into @mtholder's suggestion about calling `node_info` with a GBIF source_id (above).

I'm also going to take a look at the degree of load we can handle using our new software/new machines.

**Comment by bredelings** [comment]
OK, so you can now do this:

`curl https://api.opentreeoflife.org/v3/tree_of_life/node_info -d '{"source_id":"gbif:1206"}'`

**Comment by wellcaffeinated** [comment]
That's great!
Any news on the server load considerations? We're hoping to launch in a few weeks

**Comment by wellcaffeinated** [comment]
Hey there!
If needed we could set up our own cache server in between to reduce your server load. Should I go ahead and set that up or are you working on a solution already?

**Comment by jar398** [comment]
I'm just butting in here - I'll let others answer your question - but did you consider setting up your own instance of the open tree services that you want to use?

**Comment by mtholder** [comment]
Hi, @wellcaffeinated . If it is easy for you to set up a cache server, that would certainly be great from our perspective. We have made some progress speeding up the web services, but I'm not 100% sure that we can handle the traffic that your app may send our way. We still need to deploy the latest fixes to the production machine to see if the speed-ups on those machines that I'm seeing locally. I'm hoping to do that deployment tomorrow.

**Comment by wellcaffeinated** [comment]
Ok thanks! let me know how it goes

**Comment by mtholder** [comment]
Hi again, @bredelings deployed some of our new optimizations onto api.opentreeoflife.org. He has gotten response rates of up to 240 requests/second. I think you were expecting up to an average of 13 requests/second. So, we could be close to handling it.  Of course it depends on whether the approximately 12k visits come bunched in a couple of bursts. I would expect that to be the case, unfortunately.

Or you could perhaps route all of your `tree_of_life` api calls to `https://ot39.opentreeoflife.org` so that people browsing our site don't compete with your users.  Let us know if you want to try the ot39 server. That is usually just a dev server that we use, so we'll want to be careful to make sure that it is up and running when you release.

**Comment by wellcaffeinated** [comment]
Oh that's great!
Yeah i could try the ot39 server if that makes sense for you. I'm also
estimating this based on old data. I suspect, yes, the visitors would be
bunched a bit. But this is only really an estimate for the first day.

**Comment by wellcaffeinated** [comment]
Just bumping this to let you know that we're planning to launch next week. I'm going to start routing all traffic to https://ot39.opentreeoflife.org 
will that be available perpetually? or should i route requests to the main server eventually?

**Comment by mtholder** [comment]
Thanks for the heads up. At some point, it would be good to use the main API server, but we probably have some load balancing work to do before then...
I'll leave this issue open and ping you on it later.

**Comment by wellcaffeinated** [comment]
I noticed that on your ot39 server there's a flag "response_for_mrca_of_broken_taxon" for one of the taxons (i think it was whales). I'm not really sure how to accommodate this flag in my app. I deep link to the ott ids so this change results in the node not being displayed. Is this a flag for dev only, or will it make it to the production server eventually?

**Comment by mtholder** [comment]
That flag will make it to production eventually, but the fact that you are seeing it makes me think that we are probably serving a "preview" version of the tree on ot39, not the same one that is on the main production machine. Perhaps I'll need to ask you to use ot37 or ot38. Unfortunately, one of the developers is away right now. They should return on Thursday, and I'll try to get this sorted out and let you know ASAP.

**Comment by wellcaffeinated** [comment]
Ok I think Thursday is our launch day. HAH
I'll try one of those servers for now unless i hear otherwise

**Comment by mtholder** [comment]
Oh. OK. That being the case...

I just took a look, it seemed easiest to just install only the current tree (10.4) on ot39. 
So, you should be able to use that machine for now. 
If you do see a `response_for_mrca_of_broken_taxon` flag in a response, that indicates that the taxon is not in the that version of the synthetic tree. That will happen some on tree 10.4 (but hopefully not for important, well-supported taxa like whales). The API used to just return an error code in these cases, now we return the node view of the most recent common ancestor of the taxon that was requested.

Perhaps next week, traffic from your site won't be so high that it would create problems for our normal api server. So, you could move back to moving `api.opentreeoflife.org` at that point....

@bredelings  I made some notes for you on gitter about my deployment on ot39.

**Comment by wellcaffeinated** [comment]
IMHO that way of responding to the request is a bit confusing since it's returning a different node from the intended one. I'd suggest responding with a "HTTP 301 Moved Permanently" or a "HTTP 410 Gone" would make more sense.

I'm not sure how the phylogenetics work, but if a taxon is moved to a different part of the tree, wouldn't it be the same species (hence same ottid) but just have a different lineage now?

I guess your current handling is for when a species is broken into two species, for example...?

**Comment by mtholder** [comment]
It happens if you ask for a group of lineages (e.g. a genus) but the tree finds the group to be not a monophyletic group. Some sort of 400 error would make sense if we knew that the user only wanted to know where the set of lineages belongs *if* the group is monophyletic. An error status code was our previous behavior, but feedback from users of the site (and the api) indicated that most would want be shown information about the least inclusive group on the tree that has the taxa that they asked about (along with a flag to let them know that the grouping does not exclude all other taxa).

**Comment by wellcaffeinated** [comment]
that makes sense. I was also confused by the previous error behaviour but that was because it was a 400... so I thought I did something wrong, or that there was a bug. The thing that caught me off guard about this new behaviour is that I wasn't monitoring for the new flag, so I didn't realize that the response it was giving me wasn't for the thing i requested until I did a bunch of digging. 

If the difference is highlighted a bit more it would make things a bit easier... like a 410 code with a response that tells you how to access the MRCA that's still in the tree... but I'm using the api for something very specific. So... I don't know how researchers use it.

**Comment by wellcaffeinated** [comment]
We launched! Thanks for being so helpful everyone!
In case you're interested here are the accompanying videos we made:

Why we did it:
https://www.youtube.com/watch?v=3eE2fCLay-Q

Fun video about cladistics:
https://www.youtube.com/watch?v=yyeDgBm1Du8

**Comment by mtholder** [comment]
congrats! I enjoyed the videos.
Just let us know if you appear to be running into performance issues that appear to be related to our API.

**Comment by mtholder** [comment]
Can you switch your calls back to using `api` instead of `ot39` now that you are beyond the initial launch, @wellcaffeinated ?

**Comment by wellcaffeinated** [comment]
Oops! sorry I was out of town and distracted. I'll do that now

**Comment by bredelings** [comment]
Great, thank you! :-)
