### ISSUE TITLE
Sequence and Tax file for QIIME2

### ISSUE THREAD

**Issue by MonicaSteffi** [OpenTreeOfLife/opentree#1245]
Dear All,
I would like to use OTL for qiime2 pipeline. Where can I download the supporting file. To create a qiime2 taxonomy classifier, I need sequence file in fasta format and taxonomy file. I could not find the sequence file.

**Comment by mtholder** [comment]
we don't have something on hand that can do this, but I'd be happy to write something. Can you point me to an example of the file type that you need (I know FASTA from sequence files, but I don't know how quiime2 wants a taxonomy in FASTA)?

**Comment by MonicaSteffi** [comment]
Thank you for the reply. I am sorry for the misunderstanding. I need the sequence file in fasta format and taxonomy file in tsv format. I searched for sequence file but I couldn’t get it. Sorry if I missed something. 

I have attached the link of silva database with the required format (sequence (fasta file) and taxonomy in tsv. )
https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip

**Comment by kcranston** [comment]
@MonicaSteffi - I am not sure the opentree project is suitable for what you want to do (although I might be wrong, since I don't know much about the qiime2 pipeline). Our taxonomy is available for download here: https://tree.opentreeoflife.org/about/taxonomy-version/ott3.2

We do not have a sequence file, because the inputs for generating the OpenTree synthetic tree are published phylogenies, not sequences.

**Comment by MonicaSteffi** [comment]
Thank you for the clarification @kcranston
