### ISSUE TITLE
Noob question: What does the taxon label "mrcaott" mean?

### ISSUE THREAD

**Issue by cleopatra17** [OpenTreeOfLife/opentree#1266]
There are many taxons that don't have a scientific name but just a label that starts with `mrcaott`. I tried to find more information about those taxons by checking `taxonomy.tsv` but I couldn't locate them there.

I wonder, is there a way to retrieve more metadata about those taxons, especially a scientific name?

Thank you!

**Comment by bredelings** [comment]
Good question.  Some nodes don't have a taxonomic name because they are between taxonomic levels.  For example, species groups within a genus.  Information about these nodes come from the input phylogenies, which don't have taxonomic names for internal nodes.

We wanted to find a way to name them that would be somewhat stable between versions of our synthesis tree.  The names mrcaottXottY describe the node as the most recent common ancestor (mrca) of the taxa ottX and ottY.  So, the name is also a way of finding the node on the tree.

**Comment by cleopatra17** [comment]
Excellent. Thank you @bredelings! Also congrats on the 13.4 release!
