### ISSUE TITLE
Can't create new study

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1275]
Create study is throwing an error right away if I try to create a study with https://doi.org/10.1186/1471-2164-13-626
No issues on devtree. Only error is 
"Sorry, there was an error creating this study. (No more information is available.)"

Trying to dig into it now!

**Comment by mtholder** [comment]
This is a part of the stack that has few tests in the crontest.sh that I run on my server. But I just logged into that machine, and ran the tests manually (they've been uninstalled from cron as I have had to alter that machine due to some KU IT-triggered sys admin stuff)
The set of tests that we usually run are passing, fwiw

**Comment by snacktavish** [comment]
Redis failure? Redeploy fixed it.
