### ISSUE TITLE
add links to specific trees in references list

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#510]
We need to capture the list of input trees, and the references for the studies they come from, as a snapshot that is provided along with each synthetic tree version, for provenance purposes.

Currently the tree is found [here](http://files.opentreeoflife.org/trees/) which has two problems:
1. it points to the bibliographic references page, which will change the next time a synthetic tree is released
2. that page only lists studies, not trees, so if someone wants to replicate they'll have a hard time

These could be solved by giving a pointer to a gcmdr commit (maybe a tagged one), which ought to be done in any case, but that's not a very user-friendly form. I think it would be nice to have a human-readable form of the study list, such as a snapshot of the references page, as well as a machine-readable list of trees, in priority order, readable as a spreadsheet or JSON.

**Comment by jar398** [comment]
Hoping we can do this without help from the Smith lab, but we should file a treemachine issue if something is needed on that end. 

This is important for publication, isn't it?

**Comment by kcranston** [comment]
Couple of thoughts:

* include instructions for downloading the nexson data through the APIs / peyotl
* provide a direct download link for the newicks (other formats? csv, json, bibtex)
* keep versions of this page for each release

**Comment by mtholder** [comment]
see also: https://github.com/OpenTreeOfLife/treemachine/issues/127

**Comment by jimallman** [comment]
As a partial solution, I'm adding links for each contributing **tree** to the Bibliographic References page:

![screen shot 2015-01-26 at 11 40 25 pm](https://cloud.githubusercontent.com/assets/446375/5913611/f19ef1ce-a5b4-11e4-9dec-015570772016.png)

Clicking 'Show links to included trees' shows/hides the single-tree link(s) below:
![screen shot 2015-01-26 at 11 40 15 pm](https://cloud.githubusercontent.com/assets/446375/5913613/f1a618fa-a5b4-11e4-9f19-d2424f22e7e0.png)

Clicking any single-tree link shows the current tree (**not** necessarily the version in synthesis) in the curation app. Here are some possible improvements:

 - Show a friendlier label for the tree, instead of its raw id. @josephwb, @chinchliff: How hard would it be to add the tree '@label' property to tree metadata in **oti**?

 - Can we show the version of the tree that actually contributed to synthesis, if it's changed since then? _Should_ we? Or should this link **download** a single tree instead of showing it in the tree viewer? 

This is live on **devtree** for review. Suggestions welcome!

**Comment by jar398** [comment]
I wonder if it should just say 'Included tree' when there is only one tree,
and reserve the current behavior ('Show links to included trees (2)') for
when there are two or more. Or, since th case of 2 is so rare, just
'Included tree tree123' and 'Included tree tree456' or something like that,
without expand/contract option.

This also makes me think the tree view should show tree metadata, so you
don't have to click the x to see it. But I don't know, that takes real
estate away from the tree itself.

**Comment by jar398** [comment]
As far as I'm concerned, this one's ready to merge, so I'm going to remove the 'needs discussion' label
