### ISSUE TITLE
Waiver explanation is unclear (curation app)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#521]
_Email from @rgazis:_ 

In metadata the waiver section should be explain better. For instance “we” as curators and not authors of the article, which option should we select?

**Comment by jar398** [comment]
Since "we" doesn't occur on the page any more, and I don't see what's confusing, can we close this issue?

( ) I am an author, or can act on behalf of the authors, to apply a CC0 waiver to these data
[ ] By clicking this checkbox, I hereby release these data under the terms of the Creative Commons Zero (CC0) waiver.

**Comment by jimallman** [comment]
Agreed, these choices seem pretty clear to me. @rgazis?
