### ISSUE TITLE
info on preferred tree lost in the new curation app?

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#547]
This might be a little too late, but I noticed that the information on preferred tree (in a study with multiple trees) has not been recovered in the new curation tool. In the studies I uploaded, these were tagged with a "choose me" label.

![preferredtree_info_lost](https://cloud.githubusercontent.com/assets/6391539/5760034/f279e0e0-9c9f-11e4-9860-4d8b8f81c63e.jpg)
The same study in the new curation tool had no preferred tree (now it does because I selected).
https://tree.opentreeoflife.org/curator/study/edit/pg_485/?tab=trees

Thanks,

Romina

**Comment by jimallman** [comment]
I see that the "Choose me" tag has been preserved (see the Properties tab in this tree popup):
https://tree.opentreeoflife.org/curator/study/edit/pg_485?tab=trees&tree=tree651

But no, we don't currently recognize these tag values (on import from phylografter) and automatically mark the tagged trees as preferred. Should we?

**Comment by jimallman** [comment]
I think this issue is now moot, since we use a combination of validation/fitness testing of each tree, plus an explicit choice to include (or reasons to exclude). This might still leave some work to be done for trees have a "choose me" or similar tags, but this is trivial (in the curator) and probably best done manually. Other opinions welcome!
