### ISSUE TITLE
Failure during test deployment (ncl-build-static)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#564]
It seems like there are untested changes to the ncl installation in opentree. Maybe one of the [recent changes here](https://github.com/mtholder/ncl/commits/master)? Please disregard if I'm mistaken or if these are known issues.
```
$ ./push.sh -c ../../deployed-systems/development/devtree.config

... tons of stuff, then failure ...

/usr/include/c++/4.7/fstream:588:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::basic_ofstream<char>&’
make[3]: Leaving directory `/home/opentree/repo/opentree/curator/build-ncl-static/example/find-unsupported-edges'
make[3]: *** [findunsupportededges-findunsupportededges.o] Error 1
make[2]: Leaving directory `/home/opentree/repo/opentree/curator/build-ncl-static/example'
make[1]: Leaving directory `/home/opentree/repo/opentree/curator/build-ncl-static'
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
+ exit
```

**Comment by mtholder** [comment]
sorry bout that. should have checked on gcc 4.7

This should be fixed now with https://github.com/mtholder/ncl/commit/859d9cbda3643d3e00db0080196a4defce189108

I'll try to remember to add new stuff on a branch of ncl in the future. NCL doesn't change often.

We might want to peg a version of NCL that works for us in `opentree/curator/install-ncl.sh` rather than always running `git clone` or `git pull origin master`

**Comment by jimallman** [comment]
All better, thanks @mtholder!
