### ISSUE TITLE
Figure out where to store tree collections

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#583]
That is, the metadata and tree lists, not the trees themselves.
Options: phylesystem, a parallel git repo managed by peyotl software, auxiliary files directory, relational database...

**Comment by kcranston** [comment]
I thought we discussed this on a software call and decided to put them in a separate repo.

**Comment by jimallman** [comment]
Agreed. I've created a [`collections` repository](https://github.com/OpenTreeOfLife/collections) for this purpose. The OpenTree webapps should be able to use the GitHub APIs to contribute and moderate collections in this repository.

N.B. I've chosen a public-domain waiver for the collection data, using the [un-license](http://unlicense.org/) suggested by GitHub. Should this be [cc0](https://creativecommons.org/publicdomain/zero/1.0/) instead?

**Comment by jar398** [comment]
We can reuse major parts of peyotl for this purpose, right?

**Comment by jimallman** [comment]
> We can reuse major parts of peyotl for this purpose, right?

The use cases here are much simpler, so peyotl might be overkill. But I'll definitely take a look and see how much it assumes sharding and other complications.

**Comment by jimallman** [comment]
After a more careful review of peyotl and phylesystem-api, I'm still uncertain of the best way forward. Here are the options I'm weighing:

1. Manage collections directly in the curation webapp, using our existing credentials and GitHub API calls to store, retrieve, and search collections. This should suffice, since the files are tiny and a single repo should be sufficient. Collections would not be part of the Open Tree APIs, but could be fetched and used pretty easily using "raw" GitHub URLs.

2. We could extend **phylesytem-api** to handle collections as well as studies. This would provide a fairly uniform, RESTful API for studies, trees, and collections. Behind the scenes, the phylesystem-api would use largely separate code and GitHub APIs as described above.

3. We could extend peyotl to manage collections as a new resource type. This seems like overkill to me, since peyotl is largely concerned with complexities like shards, local and mirror repos, validation, format conversion, etc. But maybe I'm wrong, and this would be a simple addition.

@mtholder, @snacktavish, @jar398, @kcranston: Thoughts welcome!

**Comment by jar398** [comment]
The concurrency control issues are the same with collections and studies,
and validation is as much a concern for both. Access control is another
important service it provides (changes to the repo that would not be
authorized if attempted directly by the user). I wasn't suggesting using
all of peyotl, rather that there ought to be separable modules in peyotl
that could be used for these important purposes.

As for a collections API, I think API access would be quite useful, e.g.
for gmcdr and similar tools, but this is not a top priority.

**Comment by mtholder** [comment]
I agree with @jar398 that we should use part of peyotl. I think that we should take the current GitAction class in `peyotl/phylesystem/git_actions.py` and refactor it to move the more generic stuff to a base class. Then we have the basic interactions with git and locking for concurrency dealt with in the same code base.
We could have a thin adaptor layer for webservices in either the curator app or the phylesystem-api.
Logically, it makes sense to have the server side be in the curator app server, but might want to just co-locate it with the phylesystem-api server for the time being just because the deployment issues for the collection interface and the phylesystem seem like they will be quite similar.

**Comment by jimallman** [comment]
> As for a collections API, I think API access would be quite useful, e.g. for gmcdr and similar tools, but this is not a top priority

I've generally assumed that if we put this functionality into peyotl, we'd also add it to the phylesystem-api, and the curation app would use its services.

This raises a broader conceptual question: Do we consider collections to be a part of phylesystem? Or something more peripheral, like external annotations, tree illustrations, etc.?

**Comment by jar398** [comment]
On Sat, Feb 21, 2015 at 12:22 PM, Jim Allman <notifications@github.com>
wrote:

> As for a collections API, I think API access would be quite useful, e.g.
> for gmcdr and similar tools, but this is not a top priority
>
> I've generally assumed that if we put this functionality into peyotl, we'd
> also add it to the phylesystem-api, and the curation app would use its
> services.
>
I don't see that as appropriate. The code used in the implementation would
be the peyotl library, but the artifact is the collections collection, not
phylesystem. It could be cohosted with phylesystem in addition to sharing
code, but there is no shared state, and I think a different prefix on the
API URLs would be in order.

> This raises a broader conceptual question: Do we consider collections to
> be a part of phylesystem? Or something more peripheral, like external
> annotations, tree illustrations, etc.?
>
Collections are just like studies in that they are products of curation
efforts. So they deserve all the care that studies do. Not sure what you
mean by external annotations but if they are external to Open Tree then
they're not our business. I wouldn't think that a tree illustration would
be 'peripheral' - they are a lot of work to prepare and for many people
they will be 'central'. But I haven't been involved in that effort and have
no idea what the requirements are.

We had agreed that the collections would go in their own repo, separate
from phylesystem, so they are not 'part of' phylesystem in that sense. But
this is a matter of definition. I anticipate some people might think
'phylesystem' means all persistent curated artifacts belonging to Open
Tree. I think it's the architecture that matters, not so much what things
are called.

Jonathan

**Comment by jimallman** [comment]
> We had agreed that the collections would go in their own repo, separate from phylesystem, so they are not 'part of' phylesystem in that sense. But this is a matter of definition. I anticipate some people might think 'phylesystem' means all persistent curated artifacts belonging to Open Tree.

Agreed on the separate collections repo, and on the importance of collections and illustrations (all of which represent significant user effort). I wanted to clarify the boundaries between peyotl, phylesystem, and the phylesystem-api webapp. Strictly speaking, phylesystem manages trees and studies, but our URL patterns have always implied other resource types, and the v2 APIs (as presented to a consumer) blur these boundaries completely.

Here's a proposed API for collections (2df25e7cc75e77c003f3f7daa62df77c5845c318), basically a simplified clone of the API for studies, as it would appear in the [Open Tree of Life APIs](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs) wiki page. (**N.B.** This implies a collections index, which might not be requirement in the initial rollout of collections. But a RESTful API for CRUD operations seems like the minimum.)

-----

## <a name='collections'></a>Lists of useful trees
Many practical applications using OpenTree data (including [synthesis of the draft tree](http://www.biorxiv.org/content/early/2014/12/05/012260)) begin with a curated collection of trees. This is a ranked list of suitable trees, with ranking and rationale for each included tree. The code for this API is in [this Github repository](https://github.com/OpenTreeOfLife/phylesystem-api).

| URL                                        | Verb   | Summary                |
| -------------------------------------------|--------|------------------------|
|[`/collections/find_collections`](#find_collections) | POST | Return a list of collections that match a given property. If no property provided, returns a list of all collections. |
|[`/collections/properties`](#properties) | POST | Return a list of properties that can be used to search collections. |
|[`/collection/{OWNER_ID}/{COLLECTION_NAME}`](#collection) | GET | Return a collection (curated list of trees). |

**Comment by jimallman** [comment]
> I agree with @jar398 that we should use part of peyotl. I think that we should take the current GitAction class in peyotl/phylesystem/git_actions.py and refactor it to move the more generic stuff to a base class. Then we have the basic interactions with git and locking for concurrency dealt with in the same code base.

Thanks, @mtholder. I'll review the peyotl code and see if I can sort this out.

> We could have a thin adaptor layer for webservices in either the curator app or the phylesystem-api.
Logically, it makes sense to have the server side be in the curator app server, but might want to just co-locate it with the phylesystem-api server for the time being just because the deployment issues for the collection interface and the phylesystem seem like they will be quite similar.

Currently the webapp deployment for **tree.opentreeoflife.org** does install peyotl (to support the `to_nexml` conversion method). So these apps could manage collections without involving the normal API server. But that seems odd to me, since all our existing APIs are available for wider use on **api.opentreeoflife.org**. Maybe I'm misunderstanding what you mean by "adaptor " and "server side" here?

**Comment by kcranston** [comment]
Can this issue be closed? Collections being stored in https://github.com/OpenTreeOfLife/collections-0 (but is this a testing repo and we still need a production repo?)

**Comment by jimallman** [comment]
Closing this (but noting that @kcranston is correct that we'll need to create a production repo 'collections-1')
