### ISSUE TITLE
Cache the Bibliographic References page

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#602]
This is a heavy fetch, should be cacheable in RAM. 

This would be reset each time we restart apache. @jar398, do we have a post-synthesis checklist that includes (or should include) apache restart?

**Comment by jar398** [comment]
We have no checklist for such a rare event - the checklist would be lost or
forgotten at the point where we would need it. But it would surprise me if
we didn't do this when the time comes. The list will certainly be checked
in the UI as part of overall testing, so if it's wrong we will probably
remember to restart apache in order to fix it.

**Comment by jimallman** [comment]
While the [page is still constructed in web2py](https://github.com/OpenTreeOfLife/opentree/blob/477c1e72596227e46fedadec630650d1dded8db2/webapp/controllers/about.py#L419), we now use a cached URL to fetch the list of bibliographic sources from web2py's RAM cache.
```config
getSynthesisSourceList_url: {CACHED_treemachine_domain}/v3/tree_of_life/about
```
This is automatically refreshed during routine deployment.
