### ISSUE TITLE
Clearer path to upload studies from tree

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#661]
Currently you need to click on "studies" and then choose 'study curator' or 'phylographter'. It's a bit confusing and non-intuitive. 
An "Upload trees" button taking you to the curator would be nice, and I'm not sure we need the phylografter link.

**Comment by mtholder** [comment]
I agree. 

When I have http://tree.opentreeoflife.org open an half-screen, the current black menu banner at the top reconfigures to a menu which appears on click (because there is not enough space to show all menu items). That (minor) issue is discussed some on https://github.com/OpenTreeOfLife/opentree/issues/259.

I wonder if we could:
   1. remove `Home` (or make the icon clickable for the 'take me to the root' functionality).
   2. put the `Contact` and `Blog` items into `About`
   3. Change the `Source trees` menu to an `Add tree` button that directs the user to either the curator app, or a page that explains the curation process

That might address @snacktavish's comment and https://github.com/OpenTreeOfLife/opentree/issues/259.

**Comment by kcranston** [comment]
I've removed Home, replaced Source trees menu with 'Add tree' option. I'd like to keep the Feedback and Blog in the main menu (and it looks like the total width of the menu items isn't the driving factor for deciding when to switch to the narrow screen).

**Comment by kcranston** [comment]
Does the Add / Browse trees menu item suffice? Can I close this?

**Comment by snacktavish** [comment]
Yes! Thanks.
