### ISSUE TITLE
return to opentree webapp after authentication

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#685]
After first giving github access to the opentree webapp, the user is forwarded to github.com, not back to tree.opentreeoflife.org. This is going to be confusing for many. Can we change this behaviour?

**Comment by kcranston** [comment]
Looks like this is defined in two places:
* the authorization callback URL in the GitHub interface
* the config file (which overrides the value defined in the GitHub UI)

In our case, both of these are set to the same URL, http://{dev}tree.opentreeoflife.org/{opentree|curator}/user/login. The /user/login page forwards to github, so perhaps this is the problem?

**Comment by kcranston** [comment]
Tested locally:
* revoked access to devtree.opentreeoflife.org on my personal github account
* changed authorization callback URL to http://devtree.opentreeoflife.org
* changed callback URL in config file to http://devtree.opentreeoflife.org
* login, which re-directed to devtree, not github

**Comment by jimallman** [comment]
Ah, perhaps I'm mis-remembering the OAuth dance. Can you put this on a branch for review?

**Comment by kcranston** [comment]
None of this information is in the repo. The config.example does not contain a real URL, and the GitHub UI change is well, through the GitHub UI.

**Comment by jimallman** [comment]
I see what you mean. :)

**Comment by kcranston** [comment]
I think these URLs are also in [push.sh](https://github.com/OpenTreeOfLife/opentree/blob/master/deploy/push.sh#L98-L101) and in the deployed-systems repo, e.g. [for devtree](https://github.com/OpenTreeOfLife/deployed-systems/blob/master/development/devtree.config#L17-L26)

**Comment by kcranston** [comment]
tested this fix on devtree, and it works

**Comment by jimallman** [comment]
**UPDATE**: This turned out to be an unrelated bug in the commenting tool of our synth-tree viewer (main webapp). The old `redirect_uri` settings were correct, but proper behavior depends on **always** having a proper destination (called `_next`) in the query string of the initial login URL, e.g.
```
https://devtree.opentreeoflife.org/user/login?_next=https://devtree.opentreeoflife.org/opentree/opentree3.0@16560/Bryophyta
``` 
In testing, we realized that the curation app had clean and reliable login behavior, so we took a closer look at the Javascript code used in the synth-tree viewer and realized that login links weren't always being updated properly.

See #697 for a simple fix that restored proper login from the synth-tree viewer.
