### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#716]
When retrieving studies from TreeBase which License information should I select? I wonder if this need more explaining for people like me that know nothing about licensing.

**Comment by kcranston** [comment]
Hi Romina,
We recently updated the text for the licenses to better reflect what is normal for TreeBASE (you may not have noticed, since you are probably used to what it said before). Once you select the import from TreeBASE option, the text changes to the following:

<img width="658" alt="screen shot 2015-08-26 at 9 10 01 am" src="https://cloud.githubusercontent.com/assets/312034/9495690/6c2ff654-4bd2-11e5-851d-d7e109ddd83d.png">

If this is still unclear, let me know how we could change it to be more helpful / more obvious. 

Thanks!

**Comment by rgazis** [comment]
Hi Karen

I guess I have been selecting the wrong option (#2) oooppss, I did not pay attention to the "highly unusual for TreeBASE data". I think with the explanation given, it should be clear to users which option to select.
