### ISSUE TITLE
documentation for option in Edit Tree / Properties tab

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#767]
Is there a place containing the explanation for the two options below? For example what is the purpose of those "tests"?

"MRCA for this tree's ingroup (from taxonomy)": --> test
"MRCA for this tree's ingroup (from latest synthetic tree):" --> test

For the tree that I am curating now, when clicking the button TEST, I get the correct MRCA - in both cases- but I wonder what would happen in case the MRCA is not the one expected, what should the curator do?

Romina

**Comment by jar398** [comment]
Yes, this part of the UI should be made more self-explanatory. Maybe there could be a common heading "Consistency checks" for these two, and they could be described more precisely as

"MRCA in taxonomy of OTUs in this tree's ingroup": --> test
"MRCA in synthetic tree of OTUs in this tree's ingroup:" --> test

followed (or preceded) by explanatory text to the effect that if the MRCA is much more inclusive than expected, then one or more of the OTU mappings is probably incorrect, due to overzealous fuzzy matching, incorrect choice between homonyms, or an error in the taxonomy. The fix is to change or remove the mapping.

(but as discussed in #769, it is unfortunate that we can't explain *which* mapping is probably incorrect. discuss that question under #769.)

**Comment by jimallman** [comment]
Here's a mockup based on @jar398's proposed solution. Thoughts?
![screen shot 2016-01-13 at 11 54 52 am](https://cloud.githubusercontent.com/assets/446375/12301161/a40c4d4c-b9ec-11e5-9a30-fe23cbf0abe1.png)

**Comment by jimallman** [comment]
I've created a feature branch for the changes above, and merged it onto **devtree**. (I figure it's no worse than we have now.) Suggestions welcome!
