### ISSUE TITLE
MCRA in a Trichoderma study results in  Opisthokonta

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#774]
Should map to Hypocreaceae 

https://tree.opentreeoflife.org/curator/study/edit/pg_2466/?tab=trees&tree=tree5304

R

**Comment by jar398** [comment]
The problem seems to be this OTU:

```"otu358213": {
"^ot:originalLabel": "Trichoderma costaricensis", 
"^ot:ottId": 5026266, 
"^ot:ottTaxonName": "Chelopistes costaricensis", 
"^ot:treebaseOTUId": "Tl1032748"```

I don't know how this assignment was made; the epithets match, but that's certainly not enough to determine a correct match. As it turns out Chelopistes costaricensis is a thrip (an insect), so certainly not appropriate here.

Trichoderma costaricensis is not known to OTT 2.9.

Maybe fuzzy matching was used without checking all the results?

**Comment by jar398** [comment]
Not sure how to close this issue.  I can go and fix the OTU mapping, but the fact remains that we need to make it harder for curators to make this kind of mistake. Here are two ideas:
1. Implement #460, so at least if there is doubt, one can do a bit of research
2. Make it much harder for curators to overlook or bypass the set TNRS context step

**Comment by jar398** [comment]
this is the same underlying issue as #769

**Comment by jar398** [comment]
I've repaired the OTU mapping for pg_2466. Will move my comments above to #769 and close this issue.
