### ISSUE TITLE
Debian upgrade breaks webapp: "ERROR:root:code for hash md5 was not found."

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#802]
https://gist.github.com/jar398/5cb271f92eb0f7f3df51

Seems to come from following line in install-web2py-apps.sh:

    (cd $APPROOT; pip install -r requirements.txt)

The transcript in the gist is from production (tree...), which I recently upgraded to the very latest package versions for jessie.
The problem can probably be replicated on devtree, although to control carefully it would be a good idea to make sure first that /etc/apt/sources.list and /etc/apt/sources.d/backports.list on devtree match what's on tree (unstable vs. backports). Upgrade with 'sudo apt-get update; sudo apt-get upgrade'.

Have googled a bit inconclusively. Some people say this means the python installation is messed up. I suppose we could start over with a replacement server and move everything over, if all else fails. On the other hand this could be an issue with all the servers, and I don't want to have to re-provision all of them.

The production site is up and running, so I don't think this is an immediate terrible problem, but it needs to get fixed soon, as it affects our ability to roll out changes.

I should have tested a debian upgrade on devtree first. Usually this kind of thing doesn't happen with point releases of debian.

**Comment by jimallman** [comment]
I believe the crux of the transcript is here:
```log
ImportError: cannot import name md5
```
Apparently this is either a built-in python module that's been deprecated (unlikely), or one that was installed in the previous environment and is not in our requirements..? I'll chase this.

**Comment by jimallman** [comment]
Wow, [we've been here before](https://github.com/OpenTreeOfLife/opentree/issues/630)! This turned up in the Google results for the error message above. :smile:

**Comment by jimallman** [comment]
Indeed, the simple remedy suggested in #630 worked on this machine as well:

> rm -r venv followed by redeploy seems to have fixed the problem.

To clarify, this means to deletes the existing python virtualenv defined in `ot14:/home/opentree/venv/`. After this, I pushed the opentree webapps again, which installed all the python dependencies from scratch. Here's where the switch to debian jessie created a problem.

When the `md5` python module is installed, it checks for openssl on the system. If openssl can provide md5, the python module will delegate to its code; otherwise, it builds its own md5 implementation. When this virtualenv was first created, older debian apparently provided a solid md5, so we didn't build a python version in the module.

Apparently jessie doesn't offer the same md5 support in openssl, so we need to rebuild the python `md5` module so that it will generate its own md5 implementation. An easy way to do that is by simply clobbering the entire venv and rebuilding it from scratch. 

To confirm that the fix is solid (or that there's a problem), we can simply ssh to a server and check python for md5 within our virtualenv:
```bash
# ssh opentree@ot14
(venv)$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import md5
>>>
```
This import completed without any problems. Here's the result if the virtualenv and surrounding system are out of sync:
```bash
>>> import md5
ERROR:root:code for hash md5 was not found
 ...lots of additional chatter...
    from hashlib import md5
ImportError: cannot import name md5
>>>
```

**Comment by jimallman** [comment]
I'm not sure what else we can do about this in the long term, other than upgrading all our servers to jessie and specifying it as the assumed operating system. The key to reproducing this is to install our webapps, _then_ upgrade the underlying OS. I don't know if that's likely to ever happen again.

**Comment by jar398** [comment]
Thanks for tracking this down!

The real issue here is not going from wheezy to jessie; we did that before on all servers (except tree) with no issues. Rather it's the fact that hash functions and other security functions and protocols will be deprecated by the security community and removed, at random times. Things like this seem to happen every couple of years. I can't think of anything to do other than trying hard to remember to refresh the venv on every apt-get upgrade. I'll at least put a note in the [jessie upgrade wiki page](https://github.com/OpenTreeOfLife/germinator/wiki/Debian-upgrade-notes).

**Comment by jimallman** [comment]
I didn't know about the wiki page. Handy! Note that the actual link seems to be
https://github.com/OpenTreeOfLife/germinator/wiki/Debian-upgrade-notes:-jessie-and-openjdk-8#upgrading-the-python-virtualenv

Also, it looks like we already had [a note there about clobbering the virtualenv](https://github.com/OpenTreeOfLife/germinator/wiki/Debian-upgrade-notes:-jessie-and-openjdk-8#upgrading-the-python-virtualenv), so maybe we can consolidate them and add some style to make sure they're not missed.
