### ISSUE TITLE
Suppress unsaved-data warning when viewing a study.

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#824]
We sometimes see the unsaved-data warning (when leaving/closing the curation app) even if we're just viewing a study. This should only appear when we're editing!

<img width="928" alt="screen shot 2015-12-16 at 12 15 45 pm" src="https://cloud.githubusercontent.com/assets/446375/11848198/24d34516-a3ef-11e5-8a4f-41f996566b68.png">

**Comment by jimallman** [comment]
@kcranston, this was a trivial fix. Working now on **devtree**, see for example [L. M. Tsang, 2014](https://devtree.opentreeoflife.org/curator/study/view/ot_29).

This should show the warning if you try to leave the page when _editing_ the study, but not simply _viewing_ it.

**Comment by jar398** [comment]
I'm reopening because I just observed the following:

1. Go to study that is missing a DOI
1. Use wonderful look-up-DOI dialog to set DOI
1. Save study
1. Attempt to navigate away from page
1. Get "This page is asking you to confirm that you want to leave - data you have entered may not be saved"

I had *just* saved the edit. I shouldn't be getting told that I've entered information that's unsaved.

**Comment by jimallman** [comment]
Kind of a separate issue, but I'm looking into it. 

Ah, I see what's happening. The code for this warning got a bit more complicated because we now have the potential for unsaved changes to the study *and* a user's tree collections. I switched to a "stack" (push/pop) system for managing the warning messages, with warnings popped from the stack as changes are saved. But I'm pushing Nexson warnings promiscuously and they're accumulating (not cleared properly when we save changes). Fixing this now...

**Comment by jimallman** [comment]
> I had just saved the edit. I shouldn't be getting told that I've entered information that's unsaved.

OK, I have a fix for this (working for me on **devtree**). See my description of the problem above.
