### ISSUE TITLE
Can't root on edge if node connected to edge is root

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#919]
I haven't dug into this behavior, but it seems that the "re-root on this edge" dialogue doesn't open when you click on an edge if the tree is currently rooted on a node connected to that edge. Works fine if you randomly re-root, and then select that edge though.

**Comment by jimallman** [comment]
Yes, this was [deliberately blocked in the UI as a "no-op"](https://github.com/OpenTreeOfLife/opentree/blob/f39a47db34037ca5f86a982054aa2d34e887053f/curator/static/js/study-editor.js#L6419-L6422), but now I see that [some trees have a polytomy from the root node](https://devtree.opentreeoflife.org/curator/study/edit/pg_2606?tab=trees&tree=tree6049), so I can see why this would be useful.

Is that your thinking as well? My original concern was that this seems likely to create a pointless internal node, but maybe that's not a big deal.

**Comment by jimallman** [comment]
I've modified the code to allow re-rooting from a root-adjacent edge, unless it's already attached to an ad-hoc root (one added in the curation app) in the current tree, since that would truly be a no-op.

This is available for review on **devtree**. @snacktavish, please take a look and let me know if this addresses your concerns.

**Comment by snacktavish** [comment]
Perfecto!
