### ISSUE TITLE
Get rid of taxa no longer associated with a study

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#933]
(I thought I made an issue for this a long time ago, but cannot find it. Apologies if this is a duplicate).

Scenario: a (bad) tree with wonky labels is uploaded. It is recognized as bad and so deleted. However, all of the labels from that tree (mapped or not) remain in the "OTU Mapping" tab. This needlessly clutters things (and probably bloats the nexson file, although I have not checked that).

**Comment by jimallman** [comment]
> This needlessly clutters things (and probably bloats the nexson file, although I have not checked that).

Yes to both, actually. We're discussing this at length in issue #909, especially the case for **preserving** these "unused" OTUs, or more importantly, the work a curator may have done in mapping them to taxonomy. 

I'm closing this as a duplicate, but feel free to re-open if you feel otherwise. I believe in the other discussion we've mentioned the possibility of an explicit "purge" button in cases where the curator knows the unused OTUs are truly junk.

**Comment by josephwb** [comment]
I _knew_ it existed! Thanks for finding it @jimallman .
