### ISSUE TITLE
Search field for taxonomy browser

### ISSUE THREAD

**Issue by bredelings** [OpenTreeOfLife/opentree#941]
It would be nice to have a search field for looking up OTT id's by name.

1. Exact matching would be useful, and would maybe not be very complex (no javascript?)
2. Fuzzy matching (like on the tree viewer) would be nice, especially for long names.

**Comment by jar398** [comment]
Implementing exact match is trivial: (at the top of display_taxon_info in browse.py):

    output.write('<form action="browse"><input type="text" name="name"/></form>')

Making it look nice is harder. I may try to enlist @jimallman on that front; I tried a couple of things (like align=right) and they didn't work.

Completion and fuzzy matching require adding some JS to the page, which I resist. Since this is not a frequently requested feature, and there is higher priority work to be done, I think we should put off the completion feature until later.

Jim - if you go into that code - there's a small fix that's not worth its own PR: \n in browse_by_name should be <br/>.
