### ISSUE TITLE
improve load speed of study list, large studies

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#975]
The top-level curator page with the study list has a long load time. What can we do to improve this? If we implemented the find_studies method with pagination, would that help? 

This is also the case for large studies (for example, try loading [ot_409](https://tree.opentreeoflife.org/curator/study/view/ot_409) or [ot_308](https://tree.opentreeoflife.org/curator/study/view/ot_308)). Can we do a GET using the /meta option initially and then load the remaining data?

**Comment by mtholder** [comment]
I think that we should talk about ways to make the study list a lot faster. Pagination and making the page load with just skeleton data (followed by specific requests for more verbose output) both seem like promising strategies.

I don't actually think that it is worth our time to worry about huge trees, like ot_409 (it has 57987 OTUs, I believe). Studies of that size are not really amenable to manual curation. TBH, I don't think we should be managing trees of that size in phylesystem. Ideally, we'd have some way of using them in open tree. And I don't know where we should put them. But I tend to think of the curation piece (including phylesystem-api) as being focused on interactive curation.

**Comment by kcranston** [comment]
I think we can do something fairly simple to increase load times for large trees (by just loading metadata) and then giving users a big warning about not opening the tree window (or preventing it entirely). It would help if you could look at tree properties without opening the tree viewer.

**Comment by mtholder** [comment]
I agree that we could speed things up for huge trees. I just don't think it would help curators much. I think a study of that size is just about impossible to curate with our GUI curation tools. You have to open up the tree viewer to reroot it and choose the ingroup, and it seems like it would be very difficult to find the correct rooting point on that tree with our viewer. It would also be very hard to do OTU mapping.

**Comment by kcranston** [comment]
Are you advocating for taking large trees out of phylesystem? Or perhaps only keeping the metadata as I "yes, we know this tree exists..."

**Comment by mtholder** [comment]
I don't really mind having them in there _per se_ (though they do bring us closer to hitting size limits on GH repos)

I think that if we start getting more we should contemplate another solution for huge trees. We'd want to be able to serve them and use them. And it would be nice to have versioning of their curation. But we'd also probably want to be working with the submitters to get the scripts involved in handling them.

I think that at that scale people are using scripts to wrangle those trees. And pretty much the only way to have confidence in the name matching is to look at those scripts (or summaries from those scripts) rather than the OTU lists.  So, it sort of feels like phylesystem wasn't really designed for them, and when we accept them we miss a lot of the crucial info about the history of the tree.

**Comment by jimallman** [comment]
As a partial solution, I've implemented caching for the main study list, and more importantly, flushing this cache as part of our per-commit webhook, in the twin PRs https://github.com/OpenTreeOfLife/opentree/pull/978 and https://github.com/OpenTreeOfLife/phylesystem-api/pull/178 .

This improves the initial load time of the curation home page and paves the way for other uses, like an auto-complete feature for studies and trees when building a collection.
