### ISSUE TITLE
'Back' fails to go back to taxonomy browser from synthetic tree browser

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#995]
1. Browse a synthetic tree page
2. Click on an 'ott:' link to go to taxonomy browser
3. Click on 'View this taxon in the current synthetic tree'
4. Click 'back'
   --> 'Sorry, there was an error checking for taxon status.'

**Comment by jimallman** [comment]
Thanks. Looks like the problem that we use a redirect to expand the full argus URL, from
https://tree.opentreeoflife.org/opentree/ottol@93302
to
https://tree.opentreeoflife.org/opentree/argus/ottol@93302
The simplest fix is to specify the full URL in the taxonomy browser; otherwise we can modify the URL expansion to work in a way that doesn't add to history.

**Comment by jimallman** [comment]
Hm, it looks like even pasting the complete (expanded) argus URL in a fresh tab will redirect once. No error message, but it takes two clicks to return to the taxonomy browser. Another reason to revisit the general logic behind this redirect.

**Comment by jimallman** [comment]
I've made a tiny PR that should fix the error message (but it will still require two clicks to return to the taxo-browser).

**Comment by jimallman** [comment]
> I've made a tiny PR that should fix the error message (but it will still require two clicks to return to the taxo-browser).

The extra step in browser history should be fixed by the PR above! This is working now on **devtree**.
